sudo: required #need super user permission
services:
  - docker

before_install:
  - docker build -t kridsada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kridsada/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
  region: 'us-west-2'
  app: 'docker-react'
  edge: true
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-west-2-060634072842'
  on:
    branch: master
